#!/usr/bin/env bash

function docker_restore() {
    path_dump=$1
    encoding=$2
    path_log="${path_dump}.restore.log"
    name_container="pgsql_$(date +'%s')"
    docker run --name $name_container \
        -e POSTGRES_PASSWORD=pass \
        -e POSTGRES_INITDB_ARGS="--encoding=${encoding}" \
        -d postgres && \
        docker cp $path_dump $name_container:/dump_file && \
        echo "Restoring..." && \
        sleep 7 && \
        docker exec -i -u postgres $name_container \
            pg_restore --dbname=postgres --verbose /dump_file &>> "${path_log}";
    docker stop $name_container && docker rm $name_container;
    echo -e "\nERRORS:\n";
    cat "${path_log}" | grep "error";
    echo -e "\nRestore log saved in: $path_log \n";
}

clear;

# Load vars from .env
source "$(dirname "$0")/.env";

echo "========================================";
echo "HOST: $HOST";
echo "PORT: $PORT";
echo "USER: $USER";
# echo "PASSWORD: $PASSWORD";
echo "DATABASE: $DATABASE";
echo "SCHEMA: $SCHEMA";
echo "ENCODING: $ENCODING";
echo "========================================";

now=$(date +'%Y-%m-%d_%s');
path="${HOME}/${DATABASE}_${SCHEMA}_backups";
name_arq="${DATABASE}_${SCHEMA}_${now}";

if [ ! -d $path ]
then
    mkdir -p "$path";
fi

PGPASSWORD=$PASSWORD pg_dump \
    -h $HOST \
    -U $USER \
    -n $SCHEMA \
    --format=c \
    --encoding=$ENCODING \
    --no-tablespaces \
    --verbose \
    $DATABASE > "${path}/${name_arq}";

# zip "${path}/${name_arq}.zip" "${path}/${name_arq}";
# rm -f "${path}/${name_arq}";

echo -e "\nDump finished, dump saved in: ${path}/${name_arq}\n";

while true; do
    read -p "Restore dump with Docker to check integrity? (y/N) " yn
    case $yn in
        [Yy]* ) docker_restore "${path}/${name_arq}" "$ENCODING"; break;;
        [Nn]* ) exit;;
        * ) exit;;
    esac
done
